//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notadesigner.Tom.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GuiRunnerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuiRunnerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notadesigner.Tom.App.Properties.GuiRunnerResources", typeof(GuiRunnerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Ding {
            get {
                return ResourceManager.GetStream("Ding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream DingDing {
            get {
                return ResourceManager.GetStream("DingDing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your last work session is complete. Take a longer break to rejuvenate..
        /// </summary>
        internal static string LONG_BREAK_3 {
            get {
                return ResourceManager.GetString("LONG_BREAK_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MainIcon {
            get {
                object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for your first short break..
        /// </summary>
        internal static string SHORT_BREAK_0 {
            get {
                return ResourceManager.GetString("SHORT_BREAK_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s time for your second short break..
        /// </summary>
        internal static string SHORT_BREAK_1 {
            get {
                return ResourceManager.GetString("SHORT_BREAK_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to take your third short break..
        /// </summary>
        internal static string SHORT_BREAK_2 {
            get {
                return ResourceManager.GetString("SHORT_BREAK_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Tick {
            get {
                return ResourceManager.GetStream("Tick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your first work session has begun..
        /// </summary>
        internal static string WORK_SESSION_0 {
            get {
                return ResourceManager.GetString("WORK_SESSION_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your second work session..
        /// </summary>
        internal static string WORK_SESSION_1 {
            get {
                return ResourceManager.GetString("WORK_SESSION_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your third work session has begun..
        /// </summary>
        internal static string WORK_SESSION_2 {
            get {
                return ResourceManager.GetString("WORK_SESSION_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your final work session. Make it count!.
        /// </summary>
        internal static string WORK_SESSION_3 {
            get {
                return ResourceManager.GetString("WORK_SESSION_3", resourceCulture);
            }
        }
    }
}
